### ISSUE TITLE
java.io.IOException: Error during decompression (root 6.14)

### ISSUE THREAD

**Issue by JulienPeloton** [diana-hep/spark-root#20]
Configuration:
* OS: macOS High Sierra (10.13.5)
* JDK: 8
* Scala: 2.11
* Spark: 2.2.1
* extra-packages: org.diana-hep:root4j:0.1.6,org.diana-hep:spark-root_2.11:0.1.16

Hi!

When I try to load this [file](https://www.dropbox.com/s/yhrd5ja7khh00f4/event000001000-hits.root?dl=0) (3d coordinates of points) in a spark-shell, I get the following error:
```scala
scala> val df = spark.read.format("org.dianahep.sparkroot").load("event000001000-hits.root")
Map(path -> event000001000-hits.root)
java.io.IOException: Error during decompression (size=5013/14440)
  at org.dianahep.root4j.core.RootHDFSInputStream.slice(RootHDFSInputStream.java:354)
  at org.dianahep.root4j.proxy.TKey.getData(<generated>:107)
  at org.dianahep.root4j.proxy.TKey.getObject(<generated>:55)
  at org.dianahep.root4j.core.FileClassFactory.<init>(FileClassFactory.java:39)
  at org.dianahep.root4j.RootFileReader.init(RootFileReader.java:324)
  at org.dianahep.root4j.RootFileReader.<init>(RootFileReader.java:183)
  at org.dianahep.sparkroot.package$RootTableScan.<init>(sparkroot.scala:96)
  at org.dianahep.sparkroot.DefaultSource.createRelation(sparkroot.scala:146)
  at org.dianahep.sparkroot.DefaultSource.createRelation(sparkroot.scala:143)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:307)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
  ... 48 elided
Caused by: java.util.zip.DataFormatException: invalid distance code
  at java.util.zip.Inflater.inflateBytes(Native Method)
  at java.util.zip.Inflater.inflate(Inflater.java:259)
  at org.dianahep.root4j.core.RootHDFSInputStream.slice(RootHDFSInputStream.java:314)
  ... 59 more
```

Maybe the [file](https://www.dropbox.com/s/yhrd5ja7khh00f4/event000001000-hits.root?dl=0) is corrupted to start with, but being neither an expert nor a user of root, I cannot judge...
So any help would be appreciated!

Thanks,
Julien

**Comment by vkhristenko** [comment]
looking

**Comment by vkhristenko** [comment]
@JulienPeloton , did u use root 6.14 for this?

**Comment by vkhristenko** [comment]
from what i see yes, 

`pheader->version = 61400`

the problem with this is that ROOT has introduced _non-backward compatible_ changes since 6.12, i believe, which are not reflected here.

VK

**Comment by JulienPeloton** [comment]
@vkhristenko thanks for looking into it! Yes, the latest root version has been used.
Any patch at the horizon for spark-root, or shall I use a previous root version for the moment?

**Comment by vkhristenko** [comment]
before 6.12 should work. regarding patches for the future, depends on the needs really and a bit on the plans for the future:

- root will be introducing a lot of updates during the next shutdown of LHC for sure! Which will be non-backward compatible.
- currently all of the experiments' data is below 6.12 really...

these things need to be understood... but if there is a chance to use below 6.12, for instance 6.11 that would be optimal, _at this point_

VK

**Comment by JulienPeloton** [comment]
OK I see -- many thanks for those useful tips and being so quick to respond! 
I will stick to version 6.12 and earlier as much as possible then, and keep an eye on the future dev.

Julien

**Comment by vkhristenko** [comment]
6.11 and earlier ! 

VK

**Comment by vkhristenko** [comment]
6.12 already had some incompatible things i think....

**Comment by JulienPeloton** [comment]
Ah yes, my bad! thanks.

**Comment by vkhristenko** [comment]
thanks Julien! i will close the ticket for now

**Comment by bbockelm** [comment]
@vkhristenko - ROOT is backward-compatible: 6.14 can read out files generated by by prior releases.

In this case, a new compression algorithm was introduced.  That's a forward-compatibility issue: the older version can't read files produced by the newer version.

That said, there is a clear compression header in the buffer.  It looks like root4j is suppressing the underlying exception:

https://github.com/diana-hep/root4j/blob/master/src/main/java/org/dianahep/root4j/core/RootHDFSInputStream.java#L347

You might want to handle that case better and propagate a better exception message.

Finally - LZ4 is the new default.  You are going to hit this case a lot because root4j doesn't support LZ4.
